// -----------------------------------------------------------------------------
// dma_top — 2-channel AXI DMA controller (v2).
//
//   s_axil_*     : AXI4-Lite slave, the CSR block (rtl/csr.sv, GENERATED by
//                  reggen from specs/dma_csr.yaml — do not edit csr.sv by hand)
//   m_axi_*      : AXI4 master (shared by both channels via round-robin mux)
//   chN_m_axis_* : per-channel AXI-Stream out (MM2S mode)
//   chN_s_axis_* : per-channel AXI-Stream in  (S2MM mode)
//   irq          : level interrupt, OR of enabled channel DONE/ERROR flags
//
// Each CHn_CTRL.START is a self-clearing command bit: its W1S storage output
// feeds its own HW-clear input, so a software write produces a one-cycle pulse.
// -----------------------------------------------------------------------------
`default_nettype none

module dma_top #(
    parameter int AXIL_ADDR_WIDTH = 12,
    parameter int ADDR_WIDTH      = 32,
    parameter int DATA_WIDTH      = 32
) (
    input  wire clk,
    input  wire rst_n,

    // ---- AXI4-Lite slave (CSR) ----
    input  wire [AXIL_ADDR_WIDTH-1:0] s_axil_awaddr,
    input  wire                       s_axil_awvalid,
    output wire                       s_axil_awready,
    input  wire [31:0]                s_axil_wdata,
    input  wire [3:0]                 s_axil_wstrb,
    input  wire                       s_axil_wvalid,
    output wire                       s_axil_wready,
    output wire [1:0]                 s_axil_bresp,
    output wire                       s_axil_bvalid,
    input  wire                       s_axil_bready,
    input  wire [AXIL_ADDR_WIDTH-1:0] s_axil_araddr,
    input  wire                       s_axil_arvalid,
    output wire                       s_axil_arready,
    output wire [31:0]                s_axil_rdata,
    output wire [1:0]                 s_axil_rresp,
    output wire                       s_axil_rvalid,
    input  wire                       s_axil_rready,

    // ---- AXI4 master (shared data port) ----
    output wire [ADDR_WIDTH-1:0] m_axi_araddr,
    output wire [7:0]            m_axi_arlen,
    output wire [2:0]            m_axi_arsize,
    output wire [1:0]            m_axi_arburst,
    output wire                  m_axi_arvalid,
    input  wire                  m_axi_arready,
    input  wire [DATA_WIDTH-1:0] m_axi_rdata,
    input  wire [1:0]            m_axi_rresp,
    input  wire                  m_axi_rlast,
    input  wire                  m_axi_rvalid,
    output wire                  m_axi_rready,
    output wire [ADDR_WIDTH-1:0] m_axi_awaddr,
    output wire [7:0]            m_axi_awlen,
    output wire [2:0]            m_axi_awsize,
    output wire [1:0]            m_axi_awburst,
    output wire                  m_axi_awvalid,
    input  wire                  m_axi_awready,
    output wire [DATA_WIDTH-1:0]   m_axi_wdata,
    output wire [DATA_WIDTH/8-1:0] m_axi_wstrb,
    output wire                    m_axi_wlast,
    output wire                    m_axi_wvalid,
    input  wire                    m_axi_wready,
    input  wire [1:0]            m_axi_bresp,
    input  wire                  m_axi_bvalid,
    output wire                  m_axi_bready,

    // ---- channel 0 streams ----
    output wire [DATA_WIDTH-1:0]   ch0_m_axis_tdata,
    output wire [DATA_WIDTH/8-1:0] ch0_m_axis_tkeep,
    output wire                    ch0_m_axis_tlast,
    output wire                    ch0_m_axis_tvalid,
    input  wire                    ch0_m_axis_tready,
    input  wire [DATA_WIDTH-1:0]   ch0_s_axis_tdata,
    input  wire                    ch0_s_axis_tvalid,
    output wire                    ch0_s_axis_tready,

    // ---- channel 1 streams ----
    output wire [DATA_WIDTH-1:0]   ch1_m_axis_tdata,
    output wire [DATA_WIDTH/8-1:0] ch1_m_axis_tkeep,
    output wire                    ch1_m_axis_tlast,
    output wire                    ch1_m_axis_tvalid,
    input  wire                    ch1_m_axis_tready,
    input  wire [DATA_WIDTH-1:0]   ch1_s_axis_tdata,
    input  wire                    ch1_s_axis_tvalid,
    output wire                    ch1_s_axis_tready,

    output wire irq
);

    localparam [31:0] HW_VERSION = 32'h0002_0000;   // 2.0.0

    // ---- CSR <-> channel nets ----
    wire        c0_start, c1_start;
    wire [1:0]  c0_mode, c1_mode;
    wire [7:0]  c0_burst, c1_burst;
    wire        c0_busy, c1_busy;
    wire        c0_done_set, c1_done_set, c0_err_set, c1_err_set;
    wire        c0_done_flag, c1_done_flag, c0_err_flag, c1_err_flag;
    wire        c0_done_en, c0_err_en, c1_done_en, c1_err_en;
    wire [31:0] c0_src, c0_dst, c0_len, c1_src, c1_dst, c1_len;

    // GENERATED AXI-Lite CSR slave
    dma_csr_axil_csr u_csr (
        .s_axi_aclk         (clk),
        .s_axi_aresetn      (rst_n),
        .s_axi_awaddr       (s_axil_awaddr),
        .s_axi_awvalid      (s_axil_awvalid),
        .s_axi_awready      (s_axil_awready),
        .s_axi_wdata        (s_axil_wdata),
        .s_axi_wstrb        (s_axil_wstrb),
        .s_axi_wvalid       (s_axil_wvalid),
        .s_axi_wready       (s_axil_wready),
        .s_axi_bresp        (s_axil_bresp),
        .s_axi_bvalid       (s_axil_bvalid),
        .s_axi_bready       (s_axil_bready),
        .s_axi_araddr       (s_axil_araddr),
        .s_axi_arvalid      (s_axil_arvalid),
        .s_axi_arready      (s_axil_arready),
        .s_axi_rdata        (s_axil_rdata),
        .s_axi_rresp        (s_axil_rresp),
        .s_axi_rvalid       (s_axil_rvalid),
        .s_axi_rready       (s_axil_rready),

        .CH0_CTRL_START_clr_i (c0_start),          // self-clear: 1-cycle pulse
        .CH0_CTRL_START_o     (c0_start),
        .CH0_CTRL_MODE_o      (c0_mode),
        .CH0_CTRL_BURST_LEN_o (c0_burst),
        .CH0_STATUS_BUSY_i    (c0_busy),
        .CH0_STATUS_DONE_set_i(c0_done_set),
        .CH0_STATUS_DONE_o    (c0_done_flag),
        .CH0_STATUS_ERROR_set_i(c0_err_set),
        .CH0_STATUS_ERROR_o   (c0_err_flag),
        .CH0_SRC_ADDR_o       (c0_src),
        .CH0_DST_ADDR_o       (c0_dst),
        .CH0_LENGTH_o         (c0_len),

        .CH1_CTRL_START_clr_i (c1_start),
        .CH1_CTRL_START_o     (c1_start),
        .CH1_CTRL_MODE_o      (c1_mode),
        .CH1_CTRL_BURST_LEN_o (c1_burst),
        .CH1_STATUS_BUSY_i    (c1_busy),
        .CH1_STATUS_DONE_set_i(c1_done_set),
        .CH1_STATUS_DONE_o    (c1_done_flag),
        .CH1_STATUS_ERROR_set_i(c1_err_set),
        .CH1_STATUS_ERROR_o   (c1_err_flag),
        .CH1_SRC_ADDR_o       (c1_src),
        .CH1_DST_ADDR_o       (c1_dst),
        .CH1_LENGTH_o         (c1_len),

        .INT_EN_CH0_DONE_EN_o (c0_done_en),
        .INT_EN_CH0_ERROR_EN_o(c0_err_en),
        .INT_EN_CH1_DONE_EN_o (c1_done_en),
        .INT_EN_CH1_ERROR_EN_o(c1_err_en),
        .VERSION_i            (HW_VERSION)
    );

    // ---- per-channel AXI nets (into the mux) ----
    wire [ADDR_WIDTH-1:0] c0_araddr, c1_araddr, c0_awaddr, c1_awaddr;
    wire [7:0]  c0_arlen, c1_arlen, c0_awlen, c1_awlen;
    wire [2:0]  c0_arsize, c1_arsize, c0_awsize, c1_awsize;
    wire [1:0]  c0_arburst, c1_arburst, c0_awburst, c1_awburst;
    wire        c0_arvalid, c1_arvalid, c0_arready, c1_arready;
    wire [DATA_WIDTH-1:0] c0_rdata, c1_rdata, c0_wdata, c1_wdata;
    wire [1:0]  c0_rresp, c1_rresp, c0_bresp, c1_bresp;
    wire        c0_rlast, c1_rlast, c0_rvalid, c1_rvalid, c0_rready, c1_rready;
    wire        c0_awvalid, c1_awvalid, c0_awready, c1_awready;
    wire [DATA_WIDTH/8-1:0] c0_wstrb, c1_wstrb;
    wire        c0_wlast, c1_wlast, c0_wvalid, c1_wvalid, c0_wready, c1_wready;
    wire        c0_bvalid, c1_bvalid, c0_bready, c1_bready;

    dma_channel #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_ch0 (
        .clk(clk), .rst_n(rst_n),
        .start_i(c0_start), .mode_i(c0_mode),
        .src_addr_i(c0_src), .dst_addr_i(c0_dst), .len_bytes_i(c0_len),
        .max_burst_i(c0_burst),
        .busy_o(c0_busy), .done_o(c0_done_set), .err_o(c0_err_set),
        .m_axi_araddr(c0_araddr), .m_axi_arlen(c0_arlen),
        .m_axi_arsize(c0_arsize), .m_axi_arburst(c0_arburst),
        .m_axi_arvalid(c0_arvalid), .m_axi_arready(c0_arready),
        .m_axi_rdata(c0_rdata), .m_axi_rresp(c0_rresp), .m_axi_rlast(c0_rlast),
        .m_axi_rvalid(c0_rvalid), .m_axi_rready(c0_rready),
        .m_axi_awaddr(c0_awaddr), .m_axi_awlen(c0_awlen),
        .m_axi_awsize(c0_awsize), .m_axi_awburst(c0_awburst),
        .m_axi_awvalid(c0_awvalid), .m_axi_awready(c0_awready),
        .m_axi_wdata(c0_wdata), .m_axi_wstrb(c0_wstrb), .m_axi_wlast(c0_wlast),
        .m_axi_wvalid(c0_wvalid), .m_axi_wready(c0_wready),
        .m_axi_bresp(c0_bresp), .m_axi_bvalid(c0_bvalid), .m_axi_bready(c0_bready),
        .m_axis_tdata(ch0_m_axis_tdata), .m_axis_tkeep(ch0_m_axis_tkeep),
        .m_axis_tlast(ch0_m_axis_tlast), .m_axis_tvalid(ch0_m_axis_tvalid),
        .m_axis_tready(ch0_m_axis_tready),
        .s_axis_tdata(ch0_s_axis_tdata), .s_axis_tvalid(ch0_s_axis_tvalid),
        .s_axis_tready(ch0_s_axis_tready)
    );

    dma_channel #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_ch1 (
        .clk(clk), .rst_n(rst_n),
        .start_i(c1_start), .mode_i(c1_mode),
        .src_addr_i(c1_src), .dst_addr_i(c1_dst), .len_bytes_i(c1_len),
        .max_burst_i(c1_burst),
        .busy_o(c1_busy), .done_o(c1_done_set), .err_o(c1_err_set),
        .m_axi_araddr(c1_araddr), .m_axi_arlen(c1_arlen),
        .m_axi_arsize(c1_arsize), .m_axi_arburst(c1_arburst),
        .m_axi_arvalid(c1_arvalid), .m_axi_arready(c1_arready),
        .m_axi_rdata(c1_rdata), .m_axi_rresp(c1_rresp), .m_axi_rlast(c1_rlast),
        .m_axi_rvalid(c1_rvalid), .m_axi_rready(c1_rready),
        .m_axi_awaddr(c1_awaddr), .m_axi_awlen(c1_awlen),
        .m_axi_awsize(c1_awsize), .m_axi_awburst(c1_awburst),
        .m_axi_awvalid(c1_awvalid), .m_axi_awready(c1_awready),
        .m_axi_wdata(c1_wdata), .m_axi_wstrb(c1_wstrb), .m_axi_wlast(c1_wlast),
        .m_axi_wvalid(c1_wvalid), .m_axi_wready(c1_wready),
        .m_axi_bresp(c1_bresp), .m_axi_bvalid(c1_bvalid), .m_axi_bready(c1_bready),
        .m_axis_tdata(ch1_m_axis_tdata), .m_axis_tkeep(ch1_m_axis_tkeep),
        .m_axis_tlast(ch1_m_axis_tlast), .m_axis_tvalid(ch1_m_axis_tvalid),
        .m_axis_tready(ch1_m_axis_tready),
        .s_axis_tdata(ch1_s_axis_tdata), .s_axis_tvalid(ch1_s_axis_tvalid),
        .s_axis_tready(ch1_s_axis_tready)
    );

    dma_axi_mux #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_mux (
        .clk(clk), .rst_n(rst_n),
        .c0_araddr(c0_araddr), .c0_arlen(c0_arlen), .c0_arsize(c0_arsize),
        .c0_arburst(c0_arburst), .c0_arvalid(c0_arvalid), .c0_arready(c0_arready),
        .c0_rdata(c0_rdata), .c0_rresp(c0_rresp), .c0_rlast(c0_rlast),
        .c0_rvalid(c0_rvalid), .c0_rready(c0_rready),
        .c0_awaddr(c0_awaddr), .c0_awlen(c0_awlen), .c0_awsize(c0_awsize),
        .c0_awburst(c0_awburst), .c0_awvalid(c0_awvalid), .c0_awready(c0_awready),
        .c0_wdata(c0_wdata), .c0_wstrb(c0_wstrb), .c0_wlast(c0_wlast),
        .c0_wvalid(c0_wvalid), .c0_wready(c0_wready),
        .c0_bresp(c0_bresp), .c0_bvalid(c0_bvalid), .c0_bready(c0_bready),
        .c1_araddr(c1_araddr), .c1_arlen(c1_arlen), .c1_arsize(c1_arsize),
        .c1_arburst(c1_arburst), .c1_arvalid(c1_arvalid), .c1_arready(c1_arready),
        .c1_rdata(c1_rdata), .c1_rresp(c1_rresp), .c1_rlast(c1_rlast),
        .c1_rvalid(c1_rvalid), .c1_rready(c1_rready),
        .c1_awaddr(c1_awaddr), .c1_awlen(c1_awlen), .c1_awsize(c1_awsize),
        .c1_awburst(c1_awburst), .c1_awvalid(c1_awvalid), .c1_awready(c1_awready),
        .c1_wdata(c1_wdata), .c1_wstrb(c1_wstrb), .c1_wlast(c1_wlast),
        .c1_wvalid(c1_wvalid), .c1_wready(c1_wready),
        .c1_bresp(c1_bresp), .c1_bvalid(c1_bvalid), .c1_bready(c1_bready),
        .m_axi_araddr(m_axi_araddr), .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize), .m_axi_arburst(m_axi_arburst),
        .m_axi_arvalid(m_axi_arvalid), .m_axi_arready(m_axi_arready),
        .m_axi_rdata(m_axi_rdata), .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast), .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),
        .m_axi_awaddr(m_axi_awaddr), .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize), .m_axi_awburst(m_axi_awburst),
        .m_axi_awvalid(m_axi_awvalid), .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata), .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast), .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bresp(m_axi_bresp), .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready)
    );

    assign irq = (c0_done_flag & c0_done_en) | (c0_err_flag & c0_err_en)
               | (c1_done_flag & c1_done_en) | (c1_err_flag & c1_err_en);

endmodule
`default_nettype wire
