// -----------------------------------------------------------------------------
// dma_csr_axil_csr — AXI4-Lite CSR slave
// GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
// Block: dma_csr
// Control/status registers for the AXI DMA engine.
// data_width=32  addr_width=12
// -----------------------------------------------------------------------------
`default_nettype none

module dma_csr_axil_csr #(
    parameter int DATA_WIDTH = 32,
    parameter int ADDR_WIDTH = 12
) (
    input  wire                    s_axi_aclk,
    input  wire                    s_axi_aresetn,

    // Write address channel
    input  wire [ADDR_WIDTH-1:0]   s_axi_awaddr,
    input  wire                    s_axi_awvalid,
    output wire                    s_axi_awready,
    // Write data channel
    input  wire [DATA_WIDTH-1:0]   s_axi_wdata,
    input  wire [DATA_WIDTH/8-1:0] s_axi_wstrb,
    input  wire                    s_axi_wvalid,
    output wire                    s_axi_wready,
    // Write response channel
    output reg  [1:0]              s_axi_bresp,
    output reg                     s_axi_bvalid,
    input  wire                    s_axi_bready,
    // Read address channel
    input  wire [ADDR_WIDTH-1:0]   s_axi_araddr,
    input  wire                    s_axi_arvalid,
    output wire                    s_axi_arready,
    // Read data channel
    output reg  [DATA_WIDTH-1:0]   s_axi_rdata,
    output reg  [1:0]              s_axi_rresp,
    output reg                     s_axi_rvalid,
    input  wire                    s_axi_rready,
    output reg           CTRL_ENABLE_o,  // CTRL.ENABLE (RW)
    input  wire          CTRL_RESET_clr_i,  // CTRL.RESET (W1S) HW clear
    output reg           CTRL_RESET_o,  // CTRL.RESET (W1S) value
    output reg           CTRL_DIRECTION_o,  // CTRL.DIRECTION (RW)
    output reg  [7:0]    CTRL_BURST_LEN_o,  // CTRL.BURST_LEN (RW)
    input  wire          STATUS_BUSY_i,  // STATUS.BUSY (RO)
    input  wire          STATUS_DONE_set_i,  // STATUS.DONE (W1C) HW set
    output reg           STATUS_DONE_o,  // STATUS.DONE (W1C) value
    input  wire          STATUS_ERROR_set_i,  // STATUS.ERROR (W1C) HW set
    output reg           STATUS_ERROR_o,  // STATUS.ERROR (W1C) value
    output reg  [31:0]   SRC_ADDR_o,  // SRC_ADDR.SRC_ADDR (RW)
    output reg  [31:0]   DST_ADDR_o,  // DST_ADDR.DST_ADDR (RW)
    output reg  [31:0]   LENGTH_o,  // LENGTH.LENGTH (RW)
    output reg           INT_EN_DONE_EN_o,  // INT_EN.DONE_EN (RW)
    output reg           INT_EN_ERROR_EN_o  // INT_EN.ERROR_EN (RW)
);

    // ---- register byte offsets ----
    localparam [ADDR_WIDTH-1:0] ADDR_CTRL = 'h0;
    localparam [ADDR_WIDTH-1:0] ADDR_STATUS = 'h4;
    localparam [ADDR_WIDTH-1:0] ADDR_SRC_ADDR = 'h8;
    localparam [ADDR_WIDTH-1:0] ADDR_DST_ADDR = 'hC;
    localparam [ADDR_WIDTH-1:0] ADDR_LENGTH = 'h10;
    localparam [ADDR_WIDTH-1:0] ADDR_INT_EN = 'h14;

    // ---- AXI-Lite handshake (fully registered; no comb VALID/READY path) ----
    reg                    axi_awready, axi_wready, axi_arready;
    reg [ADDR_WIDTH-1:0]   axi_awaddr, axi_araddr;
    reg                    aw_en;

    assign s_axi_awready = axi_awready;
    assign s_axi_wready  = axi_wready;
    assign s_axi_arready = axi_arready;

    // Write address / data accept: require both AWVALID and WVALID present.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            axi_awready <= 1'b0;
            axi_wready  <= 1'b0;
            aw_en       <= 1'b1;
            axi_awaddr  <= '0;
        end else begin
            if (!axi_awready && s_axi_awvalid && s_axi_wvalid && aw_en) begin
                axi_awready <= 1'b1;
                axi_wready  <= 1'b1;
                axi_awaddr  <= s_axi_awaddr;
                aw_en       <= 1'b0;
            end else if (s_axi_bready && s_axi_bvalid) begin
                aw_en       <= 1'b1;
                axi_awready <= 1'b0;
                axi_wready  <= 1'b0;
            end else begin
                axi_awready <= 1'b0;
                axi_wready  <= 1'b0;
            end
        end
    end

    // A single-cycle write strobe: the cycle both ready and both valid hold.
    wire wr_en = axi_awready && s_axi_awvalid && axi_wready && s_axi_wvalid;
    // Per-bit write enable expanded from the byte strobes.
    wire [DATA_WIDTH-1:0] wr_be = {{8{s_axi_wstrb[3]}}, {8{s_axi_wstrb[2]}}, {8{s_axi_wstrb[1]}}, {8{s_axi_wstrb[0]}}};

    // Write response.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_bvalid <= 1'b0;
            s_axi_bresp  <= 2'b00;
        end else if (wr_en && !s_axi_bvalid) begin
            s_axi_bvalid <= 1'b1;
            s_axi_bresp  <= 2'b00;               // OKAY
        end else if (s_axi_bready && s_axi_bvalid) begin
            s_axi_bvalid <= 1'b0;
        end
    end

    // Read address accept.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            axi_arready <= 1'b0;
            axi_araddr  <= '0;
        end else if (!axi_arready && s_axi_arvalid) begin
            axi_arready <= 1'b1;
            axi_araddr  <= s_axi_araddr;
        end else begin
            axi_arready <= 1'b0;
        end
    end

    wire rd_en = axi_arready && s_axi_arvalid && !s_axi_rvalid;

    // ---- per-field storage & update logic ----
    reg  CTRL_ENABLE_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_ENABLE_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_ENABLE_q <= (CTRL_ENABLE_q & ~wr_be[0]) | (s_axi_wdata[0] & wr_be[0]);
    end
    always @(*) CTRL_ENABLE_o = CTRL_ENABLE_q;

    reg  CTRL_RESET_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_RESET_q <= 1'h0;
        else
            // HW clear wins; SW write-1 sets.
            CTRL_RESET_q <= ((wr_en && axi_awaddr == ADDR_CTRL)
                          ? (CTRL_RESET_q | (s_axi_wdata[1] & wr_be[1]))
                          : CTRL_RESET_q) & ~CTRL_RESET_clr_i;
    end
    always @(*) CTRL_RESET_o = CTRL_RESET_q;

    reg  CTRL_DIRECTION_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_DIRECTION_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_DIRECTION_q <= (CTRL_DIRECTION_q & ~wr_be[2]) | (s_axi_wdata[2] & wr_be[2]);
    end
    always @(*) CTRL_DIRECTION_o = CTRL_DIRECTION_q;

    reg [7:0] CTRL_BURST_LEN_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_BURST_LEN_q <= 8'h10;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_BURST_LEN_q <= (CTRL_BURST_LEN_q & ~wr_be[11:4]) | (s_axi_wdata[11:4] & wr_be[11:4]);
    end
    always @(*) CTRL_BURST_LEN_o = CTRL_BURST_LEN_q;

    reg  STATUS_DONE_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            STATUS_DONE_q <= 1'h0;
        else
            // HW set wins so events are never lost; SW write-1 clears.
            STATUS_DONE_q <= ((wr_en && axi_awaddr == ADDR_STATUS)
                          ? (STATUS_DONE_q & ~(s_axi_wdata[1] & wr_be[1]))
                          : STATUS_DONE_q) | STATUS_DONE_set_i;
    end
    always @(*) STATUS_DONE_o = STATUS_DONE_q;

    reg  STATUS_ERROR_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            STATUS_ERROR_q <= 1'h0;
        else
            // HW set wins so events are never lost; SW write-1 clears.
            STATUS_ERROR_q <= ((wr_en && axi_awaddr == ADDR_STATUS)
                          ? (STATUS_ERROR_q & ~(s_axi_wdata[2] & wr_be[2]))
                          : STATUS_ERROR_q) | STATUS_ERROR_set_i;
    end
    always @(*) STATUS_ERROR_o = STATUS_ERROR_q;

    reg [31:0] SRC_ADDR_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            SRC_ADDR_q <= 32'h0;
        else if (wr_en && axi_awaddr == ADDR_SRC_ADDR)
            SRC_ADDR_q <= (SRC_ADDR_q & ~wr_be[31:0]) | (s_axi_wdata[31:0] & wr_be[31:0]);
    end
    always @(*) SRC_ADDR_o = SRC_ADDR_q;

    reg [31:0] DST_ADDR_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            DST_ADDR_q <= 32'h0;
        else if (wr_en && axi_awaddr == ADDR_DST_ADDR)
            DST_ADDR_q <= (DST_ADDR_q & ~wr_be[31:0]) | (s_axi_wdata[31:0] & wr_be[31:0]);
    end
    always @(*) DST_ADDR_o = DST_ADDR_q;

    reg [31:0] LENGTH_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            LENGTH_q <= 32'h0;
        else if (wr_en && axi_awaddr == ADDR_LENGTH)
            LENGTH_q <= (LENGTH_q & ~wr_be[31:0]) | (s_axi_wdata[31:0] & wr_be[31:0]);
    end
    always @(*) LENGTH_o = LENGTH_q;

    reg  INT_EN_DONE_EN_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            INT_EN_DONE_EN_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_INT_EN)
            INT_EN_DONE_EN_q <= (INT_EN_DONE_EN_q & ~wr_be[0]) | (s_axi_wdata[0] & wr_be[0]);
    end
    always @(*) INT_EN_DONE_EN_o = INT_EN_DONE_EN_q;

    reg  INT_EN_ERROR_EN_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            INT_EN_ERROR_EN_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_INT_EN)
            INT_EN_ERROR_EN_q <= (INT_EN_ERROR_EN_q & ~wr_be[1]) | (s_axi_wdata[1] & wr_be[1]);
    end
    always @(*) INT_EN_ERROR_EN_o = INT_EN_ERROR_EN_q;

    // ---- read data mux ----
    reg [DATA_WIDTH-1:0] rd_data;
    always @(*) begin
        rd_data = {DATA_WIDTH{1'b0}};
        case (axi_araddr)
            ADDR_CTRL: begin
                rd_data[0] = CTRL_ENABLE_q;
                rd_data[1] = CTRL_RESET_q;
                rd_data[2] = CTRL_DIRECTION_q;
                rd_data[11:4] = CTRL_BURST_LEN_q;
            end
            ADDR_STATUS: begin
                rd_data[0] = STATUS_BUSY_i;
                rd_data[1] = STATUS_DONE_q;
                rd_data[2] = STATUS_ERROR_q;
            end
            ADDR_SRC_ADDR: begin
                rd_data[31:0] = SRC_ADDR_q;
            end
            ADDR_DST_ADDR: begin
                rd_data[31:0] = DST_ADDR_q;
            end
            ADDR_LENGTH: begin
                rd_data[31:0] = LENGTH_q;
            end
            ADDR_INT_EN: begin
                rd_data[0] = INT_EN_DONE_EN_q;
                rd_data[1] = INT_EN_ERROR_EN_q;
            end
            default: rd_data = {DATA_WIDTH{1'b0}};
        endcase
    end

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_rvalid <= 1'b0;
            s_axi_rresp  <= 2'b00;
            s_axi_rdata  <= '0;
        end else if (rd_en) begin
            s_axi_rvalid <= 1'b1;
            s_axi_rresp  <= 2'b00;               // OKAY
            s_axi_rdata  <= rd_data;
        end else if (s_axi_rvalid && s_axi_rready) begin
            s_axi_rvalid <= 1'b0;
        end
    end

endmodule
`default_nettype wire
