// -----------------------------------------------------------------------------
// dma_csr_reg_pkg — UVM register model
// GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
// Block: dma_csr
// Control/status registers for the AXI DMA engine.
// data_width=32  addr_width=12
// -----------------------------------------------------------------------------
`ifndef DMA_CSR_REG_PKG_SV
`define DMA_CSR_REG_PKG_SV

package dma_csr_reg_pkg;

    import uvm_pkg::*;
    `include "uvm_macros.svh"

    // -------------------------------------------------------------------------
    // CTRL @ 0x0
    // -------------------------------------------------------------------------
    class CTRL_reg extends uvm_reg;
        `uvm_object_utils(CTRL_reg)

        rand uvm_reg_field ENABLE;
        rand uvm_reg_field RESET;
        rand uvm_reg_field DIRECTION;
        rand uvm_reg_field BURST_LEN;

        function new(string name = "CTRL_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            ENABLE = uvm_reg_field::type_id::create("ENABLE");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ENABLE.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
            RESET = uvm_reg_field::type_id::create("RESET");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            RESET.configure(this, 1, 1, "W1S", 1, 1'h0, 1, 1, 0);
            DIRECTION = uvm_reg_field::type_id::create("DIRECTION");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            DIRECTION.configure(this, 1, 2, "RW", 0, 1'h0, 1, 1, 0);
            BURST_LEN = uvm_reg_field::type_id::create("BURST_LEN");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            BURST_LEN.configure(this, 8, 4, "RW", 0, 8'h10, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // STATUS @ 0x4
    // -------------------------------------------------------------------------
    class STATUS_reg extends uvm_reg;
        `uvm_object_utils(STATUS_reg)

        rand uvm_reg_field BUSY;
        rand uvm_reg_field DONE;
        rand uvm_reg_field ERROR;

        function new(string name = "STATUS_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            BUSY = uvm_reg_field::type_id::create("BUSY");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            BUSY.configure(this, 1, 0, "RO", 1, 1'h0, 1, 0, 0);
            DONE = uvm_reg_field::type_id::create("DONE");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            DONE.configure(this, 1, 1, "W1C", 1, 1'h0, 1, 1, 0);
            ERROR = uvm_reg_field::type_id::create("ERROR");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ERROR.configure(this, 1, 2, "W1C", 1, 1'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // SRC_ADDR @ 0x8
    // -------------------------------------------------------------------------
    class SRC_ADDR_reg extends uvm_reg;
        `uvm_object_utils(SRC_ADDR_reg)

        rand uvm_reg_field SRC_ADDR;

        function new(string name = "SRC_ADDR_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            SRC_ADDR = uvm_reg_field::type_id::create("SRC_ADDR");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            SRC_ADDR.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // DST_ADDR @ 0xC
    // -------------------------------------------------------------------------
    class DST_ADDR_reg extends uvm_reg;
        `uvm_object_utils(DST_ADDR_reg)

        rand uvm_reg_field DST_ADDR;

        function new(string name = "DST_ADDR_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            DST_ADDR = uvm_reg_field::type_id::create("DST_ADDR");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            DST_ADDR.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // LENGTH @ 0x10
    // -------------------------------------------------------------------------
    class LENGTH_reg extends uvm_reg;
        `uvm_object_utils(LENGTH_reg)

        rand uvm_reg_field LENGTH;

        function new(string name = "LENGTH_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            LENGTH = uvm_reg_field::type_id::create("LENGTH");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            LENGTH.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // INT_EN @ 0x14
    // -------------------------------------------------------------------------
    class INT_EN_reg extends uvm_reg;
        `uvm_object_utils(INT_EN_reg)

        rand uvm_reg_field DONE_EN;
        rand uvm_reg_field ERROR_EN;

        function new(string name = "INT_EN_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            DONE_EN = uvm_reg_field::type_id::create("DONE_EN");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            DONE_EN.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
            ERROR_EN = uvm_reg_field::type_id::create("ERROR_EN");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ERROR_EN.configure(this, 1, 1, "RW", 0, 1'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // Register block
    // -------------------------------------------------------------------------
    class dma_csr_reg_block extends uvm_reg_block;
        `uvm_object_utils(dma_csr_reg_block)

        rand CTRL_reg CTRL;
        rand STATUS_reg STATUS;
        rand SRC_ADDR_reg SRC_ADDR;
        rand DST_ADDR_reg DST_ADDR;
        rand LENGTH_reg LENGTH;
        rand INT_EN_reg INT_EN;
        uvm_reg_map default_map;

        function new(string name = "dma_csr_reg_block");
            super.new(name, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            default_map = create_map("default_map", 'h0, 4, UVM_LITTLE_ENDIAN);

            CTRL = CTRL_reg::type_id::create("CTRL");
            CTRL.configure(this, null, "");
            CTRL.build();
            default_map.add_reg(CTRL, 'h0, "RW");

            STATUS = STATUS_reg::type_id::create("STATUS");
            STATUS.configure(this, null, "");
            STATUS.build();
            default_map.add_reg(STATUS, 'h4, "RW");

            SRC_ADDR = SRC_ADDR_reg::type_id::create("SRC_ADDR");
            SRC_ADDR.configure(this, null, "");
            SRC_ADDR.build();
            default_map.add_reg(SRC_ADDR, 'h8, "RW");

            DST_ADDR = DST_ADDR_reg::type_id::create("DST_ADDR");
            DST_ADDR.configure(this, null, "");
            DST_ADDR.build();
            default_map.add_reg(DST_ADDR, 'hC, "RW");

            LENGTH = LENGTH_reg::type_id::create("LENGTH");
            LENGTH.configure(this, null, "");
            LENGTH.build();
            default_map.add_reg(LENGTH, 'h10, "RW");

            INT_EN = INT_EN_reg::type_id::create("INT_EN");
            INT_EN.configure(this, null, "");
            INT_EN.build();
            default_map.add_reg(INT_EN, 'h14, "RW");

            lock_model();
        endfunction

    endclass

endpackage

`endif // DMA_CSR_REG_PKG_SV
