/* ---------------------------------------------------------------------------
 * DMA_CSR_REGS_H — register map for 'dma_csr'
 * GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
 * Control/status registers for the AXI DMA engine.
 * data_width=32  addr_width=12
 * ------------------------------------------------------------------------- */
#ifndef DMA_CSR_REGS_H
#define DMA_CSR_REGS_H

#include <stdint.h>

#define DMA_CSR_BASE 0x000u

/* CTRL @ 0x000u — Global control. */
#define DMA_CSR_CTRL_OFFSET                      0x000u
#define DMA_CSR_CTRL_ADDR                        (DMA_CSR_BASE + 0x000u)
#define DMA_CSR_CTRL_RESET                       0x00000100u
#define DMA_CSR_CTRL_ENABLE_MASK                 0x00000001u
#define DMA_CSR_CTRL_ENABLE_SHIFT                0u
#define DMA_CSR_CTRL_ENABLE_WIDTH                1u
#define DMA_CSR_CTRL_ENABLE_GET(reg)             (((reg) & DMA_CSR_CTRL_ENABLE_MASK) >> DMA_CSR_CTRL_ENABLE_SHIFT)
#define DMA_CSR_CTRL_ENABLE_SET(val)             ((((uint32_t)(val)) << DMA_CSR_CTRL_ENABLE_SHIFT) & DMA_CSR_CTRL_ENABLE_MASK)
#define DMA_CSR_CTRL_RESET_MASK                  0x00000002u
#define DMA_CSR_CTRL_RESET_SHIFT                 1u
#define DMA_CSR_CTRL_RESET_WIDTH                 1u
#define DMA_CSR_CTRL_RESET_GET(reg)              (((reg) & DMA_CSR_CTRL_RESET_MASK) >> DMA_CSR_CTRL_RESET_SHIFT)
#define DMA_CSR_CTRL_RESET_SET(val)              ((((uint32_t)(val)) << DMA_CSR_CTRL_RESET_SHIFT) & DMA_CSR_CTRL_RESET_MASK)
#define DMA_CSR_CTRL_DIRECTION_MASK              0x00000004u
#define DMA_CSR_CTRL_DIRECTION_SHIFT             2u
#define DMA_CSR_CTRL_DIRECTION_WIDTH             1u
#define DMA_CSR_CTRL_DIRECTION_GET(reg)          (((reg) & DMA_CSR_CTRL_DIRECTION_MASK) >> DMA_CSR_CTRL_DIRECTION_SHIFT)
#define DMA_CSR_CTRL_DIRECTION_SET(val)          ((((uint32_t)(val)) << DMA_CSR_CTRL_DIRECTION_SHIFT) & DMA_CSR_CTRL_DIRECTION_MASK)
#define DMA_CSR_CTRL_DIRECTION_MEM_TO_DEV        0x00000000u  /* Read memory, write device. */
#define DMA_CSR_CTRL_DIRECTION_DEV_TO_MEM        0x00000001u  /* Read device, write memory. */
#define DMA_CSR_CTRL_BURST_LEN_MASK              0x00000FF0u
#define DMA_CSR_CTRL_BURST_LEN_SHIFT             4u
#define DMA_CSR_CTRL_BURST_LEN_WIDTH             8u
#define DMA_CSR_CTRL_BURST_LEN_GET(reg)          (((reg) & DMA_CSR_CTRL_BURST_LEN_MASK) >> DMA_CSR_CTRL_BURST_LEN_SHIFT)
#define DMA_CSR_CTRL_BURST_LEN_SET(val)          ((((uint32_t)(val)) << DMA_CSR_CTRL_BURST_LEN_SHIFT) & DMA_CSR_CTRL_BURST_LEN_MASK)

/* STATUS @ 0x004u — Engine status (hardware-driven). */
#define DMA_CSR_STATUS_OFFSET                    0x004u
#define DMA_CSR_STATUS_ADDR                      (DMA_CSR_BASE + 0x004u)
#define DMA_CSR_STATUS_RESET                     0x00000000u
#define DMA_CSR_STATUS_BUSY_MASK                 0x00000001u
#define DMA_CSR_STATUS_BUSY_SHIFT                0u
#define DMA_CSR_STATUS_BUSY_WIDTH                1u
#define DMA_CSR_STATUS_BUSY_GET(reg)             (((reg) & DMA_CSR_STATUS_BUSY_MASK) >> DMA_CSR_STATUS_BUSY_SHIFT)
#define DMA_CSR_STATUS_BUSY_SET(val)             ((((uint32_t)(val)) << DMA_CSR_STATUS_BUSY_SHIFT) & DMA_CSR_STATUS_BUSY_MASK)
#define DMA_CSR_STATUS_DONE_MASK                 0x00000002u
#define DMA_CSR_STATUS_DONE_SHIFT                1u
#define DMA_CSR_STATUS_DONE_WIDTH                1u
#define DMA_CSR_STATUS_DONE_GET(reg)             (((reg) & DMA_CSR_STATUS_DONE_MASK) >> DMA_CSR_STATUS_DONE_SHIFT)
#define DMA_CSR_STATUS_DONE_SET(val)             ((((uint32_t)(val)) << DMA_CSR_STATUS_DONE_SHIFT) & DMA_CSR_STATUS_DONE_MASK)
#define DMA_CSR_STATUS_ERROR_MASK                0x00000004u
#define DMA_CSR_STATUS_ERROR_SHIFT               2u
#define DMA_CSR_STATUS_ERROR_WIDTH               1u
#define DMA_CSR_STATUS_ERROR_GET(reg)            (((reg) & DMA_CSR_STATUS_ERROR_MASK) >> DMA_CSR_STATUS_ERROR_SHIFT)
#define DMA_CSR_STATUS_ERROR_SET(val)            ((((uint32_t)(val)) << DMA_CSR_STATUS_ERROR_SHIFT) & DMA_CSR_STATUS_ERROR_MASK)

/* SRC_ADDR @ 0x008u — Source byte address (whole-register field). */
#define DMA_CSR_SRC_ADDR_OFFSET                  0x008u
#define DMA_CSR_SRC_ADDR_ADDR                    (DMA_CSR_BASE + 0x008u)
#define DMA_CSR_SRC_ADDR_RESET                   0x00000000u
#define DMA_CSR_SRC_ADDR_MASK                    0xFFFFFFFFu
#define DMA_CSR_SRC_ADDR_SHIFT                   0u
#define DMA_CSR_SRC_ADDR_WIDTH                   32u
#define DMA_CSR_SRC_ADDR_GET(reg)                (((reg) & DMA_CSR_SRC_ADDR_MASK) >> DMA_CSR_SRC_ADDR_SHIFT)
#define DMA_CSR_SRC_ADDR_SET(val)                ((((uint32_t)(val)) << DMA_CSR_SRC_ADDR_SHIFT) & DMA_CSR_SRC_ADDR_MASK)

/* DST_ADDR @ 0x00Cu — Destination byte address (whole-register field). */
#define DMA_CSR_DST_ADDR_OFFSET                  0x00Cu
#define DMA_CSR_DST_ADDR_ADDR                    (DMA_CSR_BASE + 0x00Cu)
#define DMA_CSR_DST_ADDR_RESET                   0x00000000u
#define DMA_CSR_DST_ADDR_MASK                    0xFFFFFFFFu
#define DMA_CSR_DST_ADDR_SHIFT                   0u
#define DMA_CSR_DST_ADDR_WIDTH                   32u
#define DMA_CSR_DST_ADDR_GET(reg)                (((reg) & DMA_CSR_DST_ADDR_MASK) >> DMA_CSR_DST_ADDR_SHIFT)
#define DMA_CSR_DST_ADDR_SET(val)                ((((uint32_t)(val)) << DMA_CSR_DST_ADDR_SHIFT) & DMA_CSR_DST_ADDR_MASK)

/* LENGTH @ 0x010u — Transfer length in bytes. */
#define DMA_CSR_LENGTH_OFFSET                    0x010u
#define DMA_CSR_LENGTH_ADDR                      (DMA_CSR_BASE + 0x010u)
#define DMA_CSR_LENGTH_RESET                     0x00000000u
#define DMA_CSR_LENGTH_MASK                      0xFFFFFFFFu
#define DMA_CSR_LENGTH_SHIFT                     0u
#define DMA_CSR_LENGTH_WIDTH                     32u
#define DMA_CSR_LENGTH_GET(reg)                  (((reg) & DMA_CSR_LENGTH_MASK) >> DMA_CSR_LENGTH_SHIFT)
#define DMA_CSR_LENGTH_SET(val)                  ((((uint32_t)(val)) << DMA_CSR_LENGTH_SHIFT) & DMA_CSR_LENGTH_MASK)

/* INT_EN @ 0x014u — Interrupt enables. */
#define DMA_CSR_INT_EN_OFFSET                    0x014u
#define DMA_CSR_INT_EN_ADDR                      (DMA_CSR_BASE + 0x014u)
#define DMA_CSR_INT_EN_RESET                     0x00000000u
#define DMA_CSR_INT_EN_DONE_EN_MASK              0x00000001u
#define DMA_CSR_INT_EN_DONE_EN_SHIFT             0u
#define DMA_CSR_INT_EN_DONE_EN_WIDTH             1u
#define DMA_CSR_INT_EN_DONE_EN_GET(reg)          (((reg) & DMA_CSR_INT_EN_DONE_EN_MASK) >> DMA_CSR_INT_EN_DONE_EN_SHIFT)
#define DMA_CSR_INT_EN_DONE_EN_SET(val)          ((((uint32_t)(val)) << DMA_CSR_INT_EN_DONE_EN_SHIFT) & DMA_CSR_INT_EN_DONE_EN_MASK)
#define DMA_CSR_INT_EN_ERROR_EN_MASK             0x00000002u
#define DMA_CSR_INT_EN_ERROR_EN_SHIFT            1u
#define DMA_CSR_INT_EN_ERROR_EN_WIDTH            1u
#define DMA_CSR_INT_EN_ERROR_EN_GET(reg)         (((reg) & DMA_CSR_INT_EN_ERROR_EN_MASK) >> DMA_CSR_INT_EN_ERROR_EN_SHIFT)
#define DMA_CSR_INT_EN_ERROR_EN_SET(val)         ((((uint32_t)(val)) << DMA_CSR_INT_EN_ERROR_EN_SHIFT) & DMA_CSR_INT_EN_ERROR_EN_MASK)

#endif /* DMA_CSR_REGS_H */
