/* ---------------------------------------------------------------------------
 * TIMER_REGS_H — register map for 'timer'
 * GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
 * A simple 32-bit down-counter timer with interrupt.
 * data_width=32  addr_width=8
 * ------------------------------------------------------------------------- */
#ifndef TIMER_REGS_H
#define TIMER_REGS_H

#include <stdint.h>

#define TIMER_BASE 0x4000u

/* LOAD @ 0x00u — Counter reload value. */
#define TIMER_LOAD_OFFSET                        0x00u
#define TIMER_LOAD_ADDR                          (TIMER_BASE + 0x00u)
#define TIMER_LOAD_RESET                         0x00000000u
#define TIMER_LOAD_MASK                          0xFFFFFFFFu
#define TIMER_LOAD_SHIFT                         0u
#define TIMER_LOAD_WIDTH                         32u
#define TIMER_LOAD_GET(reg)                      (((reg) & TIMER_LOAD_MASK) >> TIMER_LOAD_SHIFT)
#define TIMER_LOAD_SET(val)                      ((((uint32_t)(val)) << TIMER_LOAD_SHIFT) & TIMER_LOAD_MASK)

/* VALUE @ 0x04u — Current counter value (hardware-driven). */
#define TIMER_VALUE_OFFSET                       0x04u
#define TIMER_VALUE_ADDR                         (TIMER_BASE + 0x04u)
#define TIMER_VALUE_RESET                        0x00000000u
#define TIMER_VALUE_MASK                         0xFFFFFFFFu
#define TIMER_VALUE_SHIFT                        0u
#define TIMER_VALUE_WIDTH                        32u
#define TIMER_VALUE_GET(reg)                     (((reg) & TIMER_VALUE_MASK) >> TIMER_VALUE_SHIFT)
#define TIMER_VALUE_SET(val)                     ((((uint32_t)(val)) << TIMER_VALUE_SHIFT) & TIMER_VALUE_MASK)

/* CTRL @ 0x08u — Timer control. */
#define TIMER_CTRL_OFFSET                        0x08u
#define TIMER_CTRL_ADDR                          (TIMER_BASE + 0x08u)
#define TIMER_CTRL_RESET                         0x00000000u
#define TIMER_CTRL_ENABLE_MASK                   0x00000001u
#define TIMER_CTRL_ENABLE_SHIFT                  0u
#define TIMER_CTRL_ENABLE_WIDTH                  1u
#define TIMER_CTRL_ENABLE_GET(reg)               (((reg) & TIMER_CTRL_ENABLE_MASK) >> TIMER_CTRL_ENABLE_SHIFT)
#define TIMER_CTRL_ENABLE_SET(val)               ((((uint32_t)(val)) << TIMER_CTRL_ENABLE_SHIFT) & TIMER_CTRL_ENABLE_MASK)
#define TIMER_CTRL_MODE_MASK                     0x00000002u
#define TIMER_CTRL_MODE_SHIFT                    1u
#define TIMER_CTRL_MODE_WIDTH                    1u
#define TIMER_CTRL_MODE_GET(reg)                 (((reg) & TIMER_CTRL_MODE_MASK) >> TIMER_CTRL_MODE_SHIFT)
#define TIMER_CTRL_MODE_SET(val)                 ((((uint32_t)(val)) << TIMER_CTRL_MODE_SHIFT) & TIMER_CTRL_MODE_MASK)
#define TIMER_CTRL_MODE_ONESHOT                  0x00000000u  /* Stop at zero. */
#define TIMER_CTRL_MODE_PERIODIC                 0x00000001u  /* Reload and continue. */
#define TIMER_CTRL_TRIGGER_MASK                  0x00000004u
#define TIMER_CTRL_TRIGGER_SHIFT                 2u
#define TIMER_CTRL_TRIGGER_WIDTH                 1u
#define TIMER_CTRL_TRIGGER_GET(reg)              (((reg) & TIMER_CTRL_TRIGGER_MASK) >> TIMER_CTRL_TRIGGER_SHIFT)
#define TIMER_CTRL_TRIGGER_SET(val)              ((((uint32_t)(val)) << TIMER_CTRL_TRIGGER_SHIFT) & TIMER_CTRL_TRIGGER_MASK)

/* INT @ 0x0Cu — Interrupt status. */
#define TIMER_INT_OFFSET                         0x0Cu
#define TIMER_INT_ADDR                           (TIMER_BASE + 0x0Cu)
#define TIMER_INT_RESET                          0x00000000u
#define TIMER_INT_FLAG_MASK                      0x00000001u
#define TIMER_INT_FLAG_SHIFT                     0u
#define TIMER_INT_FLAG_WIDTH                     1u
#define TIMER_INT_FLAG_GET(reg)                  (((reg) & TIMER_INT_FLAG_MASK) >> TIMER_INT_FLAG_SHIFT)
#define TIMER_INT_FLAG_SET(val)                  ((((uint32_t)(val)) << TIMER_INT_FLAG_SHIFT) & TIMER_INT_FLAG_MASK)
#define TIMER_INT_ACK_MASK                       0x00000002u
#define TIMER_INT_ACK_SHIFT                      1u
#define TIMER_INT_ACK_WIDTH                      1u
#define TIMER_INT_ACK_GET(reg)                   (((reg) & TIMER_INT_ACK_MASK) >> TIMER_INT_ACK_SHIFT)
#define TIMER_INT_ACK_SET(val)                   ((((uint32_t)(val)) << TIMER_INT_ACK_SHIFT) & TIMER_INT_ACK_MASK)

#endif /* TIMER_REGS_H */
