// -----------------------------------------------------------------------------
// timer_reg_pkg — UVM register model
// GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
// Block: timer
// A simple 32-bit down-counter timer with interrupt.
// data_width=32  addr_width=8
// -----------------------------------------------------------------------------
`ifndef TIMER_REG_PKG_SV
`define TIMER_REG_PKG_SV

package timer_reg_pkg;

    import uvm_pkg::*;
    `include "uvm_macros.svh"

    // -------------------------------------------------------------------------
    // LOAD @ 0x0
    // -------------------------------------------------------------------------
    class LOAD_reg extends uvm_reg;
        `uvm_object_utils(LOAD_reg)

        rand uvm_reg_field LOAD;

        function new(string name = "LOAD_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            LOAD = uvm_reg_field::type_id::create("LOAD");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            LOAD.configure(this, 32, 0, "RW", 0, 32'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // VALUE @ 0x4
    // -------------------------------------------------------------------------
    class VALUE_reg extends uvm_reg;
        `uvm_object_utils(VALUE_reg)

        rand uvm_reg_field VALUE;

        function new(string name = "VALUE_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            VALUE = uvm_reg_field::type_id::create("VALUE");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            VALUE.configure(this, 32, 0, "RO", 1, 32'h0, 1, 0, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // CTRL @ 0x8
    // -------------------------------------------------------------------------
    class CTRL_reg extends uvm_reg;
        `uvm_object_utils(CTRL_reg)

        rand uvm_reg_field ENABLE;
        rand uvm_reg_field MODE;
        rand uvm_reg_field TRIGGER;

        function new(string name = "CTRL_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            ENABLE = uvm_reg_field::type_id::create("ENABLE");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ENABLE.configure(this, 1, 0, "RW", 0, 1'h0, 1, 1, 0);
            MODE = uvm_reg_field::type_id::create("MODE");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            MODE.configure(this, 1, 1, "RW", 0, 1'h0, 1, 1, 0);
            TRIGGER = uvm_reg_field::type_id::create("TRIGGER");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            TRIGGER.configure(this, 1, 2, "WO", 0, 1'h0, 1, 1, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // INT @ 0xC
    // -------------------------------------------------------------------------
    class INT_reg extends uvm_reg;
        `uvm_object_utils(INT_reg)

        rand uvm_reg_field FLAG;
        rand uvm_reg_field ACK;

        function new(string name = "INT_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            FLAG = uvm_reg_field::type_id::create("FLAG");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            FLAG.configure(this, 1, 0, "W1C", 1, 1'h0, 1, 1, 0);
            ACK = uvm_reg_field::type_id::create("ACK");
            // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ACK.configure(this, 1, 1, "RC", 1, 1'h0, 1, 0, 0);
        endfunction

    endclass

    // -------------------------------------------------------------------------
    // Register block
    // -------------------------------------------------------------------------
    class timer_reg_block extends uvm_reg_block;
        `uvm_object_utils(timer_reg_block)

        rand LOAD_reg LOAD;
        rand VALUE_reg VALUE;
        rand CTRL_reg CTRL;
        rand INT_reg INT;
        uvm_reg_map default_map;

        function new(string name = "timer_reg_block");
            super.new(name, UVM_NO_COVERAGE);
        endfunction

        virtual function void build();
            default_map = create_map("default_map", 'h4000, 4, UVM_LITTLE_ENDIAN);

            LOAD = LOAD_reg::type_id::create("LOAD");
            LOAD.configure(this, null, "");
            LOAD.build();
            default_map.add_reg(LOAD, 'h0, "RW");

            VALUE = VALUE_reg::type_id::create("VALUE");
            VALUE.configure(this, null, "");
            VALUE.build();
            default_map.add_reg(VALUE, 'h4, "RO");

            CTRL = CTRL_reg::type_id::create("CTRL");
            CTRL.configure(this, null, "");
            CTRL.build();
            default_map.add_reg(CTRL, 'h8, "RW");

            INT = INT_reg::type_id::create("INT");
            INT.configure(this, null, "");
            INT.build();
            default_map.add_reg(INT, 'hC, "RW");

            lock_model();
        endfunction

    endclass

endpackage

`endif // TIMER_REG_PKG_SV
