// -----------------------------------------------------------------------------
// timer_axil_csr — AXI4-Lite CSR slave
// GENERATED by reggen. Do not edit by hand; edit the YAML spec and regenerate.
// Block: timer
// A simple 32-bit down-counter timer with interrupt.
// data_width=32  addr_width=8
// -----------------------------------------------------------------------------
`default_nettype none

module timer_axil_csr #(
    parameter int DATA_WIDTH = 32,
    parameter int ADDR_WIDTH = 8
) (
    input  wire                    s_axi_aclk,
    input  wire                    s_axi_aresetn,

    // Write address channel
    input  wire [ADDR_WIDTH-1:0]   s_axi_awaddr,
    input  wire                    s_axi_awvalid,
    output wire                    s_axi_awready,
    // Write data channel
    input  wire [DATA_WIDTH-1:0]   s_axi_wdata,
    input  wire [DATA_WIDTH/8-1:0] s_axi_wstrb,
    input  wire                    s_axi_wvalid,
    output wire                    s_axi_wready,
    // Write response channel
    output reg  [1:0]              s_axi_bresp,
    output reg                     s_axi_bvalid,
    input  wire                    s_axi_bready,
    // Read address channel
    input  wire [ADDR_WIDTH-1:0]   s_axi_araddr,
    input  wire                    s_axi_arvalid,
    output wire                    s_axi_arready,
    // Read data channel
    output reg  [DATA_WIDTH-1:0]   s_axi_rdata,
    output reg  [1:0]              s_axi_rresp,
    output reg                     s_axi_rvalid,
    input  wire                    s_axi_rready,
    output reg  [31:0]   LOAD_o,  // LOAD.LOAD (RW)
    input  wire [31:0]   VALUE_i,  // VALUE.VALUE (RO)
    output reg           CTRL_ENABLE_o,  // CTRL.ENABLE (RW)
    output reg           CTRL_MODE_o,  // CTRL.MODE (RW)
    output reg           CTRL_TRIGGER_o,  // CTRL.TRIGGER (WO)
    input  wire          INT_FLAG_set_i,  // INT.FLAG (RW1C) HW set
    output reg           INT_FLAG_o,  // INT.FLAG (RW1C) value
    input  wire          INT_ACK_set_i,  // INT.ACK (RC) HW set
    output reg           INT_ACK_o  // INT.ACK (RC) value
);

    // ---- register byte offsets ----
    localparam [ADDR_WIDTH-1:0] ADDR_LOAD = 'h0;
    localparam [ADDR_WIDTH-1:0] ADDR_VALUE = 'h4;
    localparam [ADDR_WIDTH-1:0] ADDR_CTRL = 'h8;
    localparam [ADDR_WIDTH-1:0] ADDR_INT = 'hC;

    // ---- AXI-Lite handshake (fully registered; no comb VALID/READY path) ----
    reg                    axi_awready, axi_wready, axi_arready;
    reg [ADDR_WIDTH-1:0]   axi_awaddr, axi_araddr;
    reg                    aw_en;

    assign s_axi_awready = axi_awready;
    assign s_axi_wready  = axi_wready;
    assign s_axi_arready = axi_arready;

    // Write address / data accept: require both AWVALID and WVALID present.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            axi_awready <= 1'b0;
            axi_wready  <= 1'b0;
            aw_en       <= 1'b1;
            axi_awaddr  <= '0;
        end else begin
            if (!axi_awready && s_axi_awvalid && s_axi_wvalid && aw_en) begin
                axi_awready <= 1'b1;
                axi_wready  <= 1'b1;
                axi_awaddr  <= s_axi_awaddr;
                aw_en       <= 1'b0;
            end else if (s_axi_bready && s_axi_bvalid) begin
                aw_en       <= 1'b1;
                axi_awready <= 1'b0;
                axi_wready  <= 1'b0;
            end else begin
                axi_awready <= 1'b0;
                axi_wready  <= 1'b0;
            end
        end
    end

    // A single-cycle write strobe: the cycle both ready and both valid hold.
    wire wr_en = axi_awready && s_axi_awvalid && axi_wready && s_axi_wvalid;
    // Per-bit write enable expanded from the byte strobes.
    wire [DATA_WIDTH-1:0] wr_be = {{8{s_axi_wstrb[3]}}, {8{s_axi_wstrb[2]}}, {8{s_axi_wstrb[1]}}, {8{s_axi_wstrb[0]}}};

    // Write response.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_bvalid <= 1'b0;
            s_axi_bresp  <= 2'b00;
        end else if (wr_en && !s_axi_bvalid) begin
            s_axi_bvalid <= 1'b1;
            s_axi_bresp  <= 2'b00;               // OKAY
        end else if (s_axi_bready && s_axi_bvalid) begin
            s_axi_bvalid <= 1'b0;
        end
    end

    // Read address accept.
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            axi_arready <= 1'b0;
            axi_araddr  <= '0;
        end else if (!axi_arready && s_axi_arvalid) begin
            axi_arready <= 1'b1;
            axi_araddr  <= s_axi_araddr;
        end else begin
            axi_arready <= 1'b0;
        end
    end

    wire rd_en = axi_arready && s_axi_arvalid && !s_axi_rvalid;

    // ---- per-field storage & update logic ----
    reg [31:0] LOAD_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            LOAD_q <= 32'h0;
        else if (wr_en && axi_awaddr == ADDR_LOAD)
            LOAD_q <= (LOAD_q & ~wr_be[31:0]) | (s_axi_wdata[31:0] & wr_be[31:0]);
    end
    always @(*) LOAD_o = LOAD_q;

    reg  CTRL_ENABLE_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_ENABLE_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_ENABLE_q <= (CTRL_ENABLE_q & ~wr_be[0]) | (s_axi_wdata[0] & wr_be[0]);
    end
    always @(*) CTRL_ENABLE_o = CTRL_ENABLE_q;

    reg  CTRL_MODE_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_MODE_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_MODE_q <= (CTRL_MODE_q & ~wr_be[1]) | (s_axi_wdata[1] & wr_be[1]);
    end
    always @(*) CTRL_MODE_o = CTRL_MODE_q;

    reg  CTRL_TRIGGER_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            CTRL_TRIGGER_q <= 1'h0;
        else if (wr_en && axi_awaddr == ADDR_CTRL)
            CTRL_TRIGGER_q <= (CTRL_TRIGGER_q & ~wr_be[2]) | (s_axi_wdata[2] & wr_be[2]);
    end
    always @(*) CTRL_TRIGGER_o = CTRL_TRIGGER_q;

    reg  INT_FLAG_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            INT_FLAG_q <= 1'h0;
        else
            // HW set wins so events are never lost; SW write-1 clears.
            INT_FLAG_q <= ((wr_en && axi_awaddr == ADDR_INT)
                          ? (INT_FLAG_q & ~(s_axi_wdata[0] & wr_be[0]))
                          : INT_FLAG_q) | INT_FLAG_set_i;
    end
    always @(*) INT_FLAG_o = INT_FLAG_q;

    reg  INT_ACK_q;
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn)
            INT_ACK_q <= 1'h0;
        else
            // A SW read clears; HW set wins.
            INT_ACK_q <= ((rd_en && axi_araddr == ADDR_INT) ? 1'h0 : INT_ACK_q) | INT_ACK_set_i;
    end
    always @(*) INT_ACK_o = INT_ACK_q;

    // ---- read data mux ----
    reg [DATA_WIDTH-1:0] rd_data;
    always @(*) begin
        rd_data = {DATA_WIDTH{1'b0}};
        case (axi_araddr)
            ADDR_LOAD: begin
                rd_data[31:0] = LOAD_q;
            end
            ADDR_VALUE: begin
                rd_data[31:0] = VALUE_i;
            end
            ADDR_CTRL: begin
                rd_data[0] = CTRL_ENABLE_q;
                rd_data[1] = CTRL_MODE_q;
            end
            ADDR_INT: begin
                rd_data[0] = INT_FLAG_q;
                rd_data[1] = INT_ACK_q;
            end
            default: rd_data = {DATA_WIDTH{1'b0}};
        endcase
    end

    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            s_axi_rvalid <= 1'b0;
            s_axi_rresp  <= 2'b00;
            s_axi_rdata  <= '0;
        end else if (rd_en) begin
            s_axi_rvalid <= 1'b1;
            s_axi_rresp  <= 2'b00;               // OKAY
            s_axi_rdata  <= rd_data;
        end else if (s_axi_rvalid && s_axi_rready) begin
            s_axi_rvalid <= 1'b0;
        end
    end

endmodule
`default_nettype wire
